Fri May 31 01:19:58 AEST 2019 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Fri May 31 01:19:58 AEST 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-016b-0953-893d-ffffe6dd6238 
on database directory D:\LTChr\Documents\UTS\UTS Yr3\Term 1\Intro to Software Dev\Assignment 2\dev-Group20\Assignment-1-demo\src\java\uts\wsd\OnlineMovieStore with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_144/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_144-b01
user.dir=C:\Program Files\Java\jdk1.8.0_144\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=D:\LTChr\Documents\UTS\UTS Yr3\Term 1\Intro to Software Dev\Assignment 2\dev-Group20\Assignment-1-demo\src\java\uts\wsd
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Fri May 31 01:20:17 AEST 2019:
Shutting down instance a816c00e-016b-0953-893d-ffffe6dd6238 on database directory D:\LTChr\Documents\UTS\UTS Yr3\Term 1\Intro to Software Dev\Assignment 2\dev-Group20\Assignment-1-demo\src\java\uts\wsd\OnlineMovieStore with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 31 01:20:17 AEST 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = OnlineMovieStore), (DRDAID = {2}), Database 'OnlineMovieStore' shutdown.
----------------------------------------------------------------
Fri May 31 01:22:30 AEST 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a65c80ac-016b-0953-893d-ffffe6dd6238 
on database directory D:\LTChr\Documents\UTS\UTS Yr3\Term 1\Intro to Software Dev\Assignment 2\dev-Group20\Assignment-1-demo\src\java\uts\wsd\OnlineMovieStore with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_144/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_144-b01
user.dir=C:\Program Files\Java\jdk1.8.0_144\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=D:\LTChr\Documents\UTS\UTS Yr3\Term 1\Intro to Software Dev\Assignment 2\dev-Group20\Assignment-1-demo\src\java\uts\wsd
Database Class Loader started - derby.database.classpath=''
Fri May 31 01:22:31 AEST 2019 Thread[DRDAConnThread_2,5,main] (XID = 182), (SESSIONID = 0), (DATABASE = OnlineMovieStore), (DRDAID = {3}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 31 01:22:31 AEST 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = OnlineMovieStore), (DRDAID = {3}), Connection authentication failure occurred.  Reason: Invalid authentication..
